version: "3.9"
services:
  warehouse:
    container_name: warehouse
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: warehouse/
      dockerfile: Dockerfile
    ports:
      - 9001:9001 #host:container
    volumes:
      - ./:/app/app