version: "3.9"
services:
  warehouse:
    container_name: warehouse
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: warehouse/
      dockerfile: Dockerfile
    ports:
      - 8080:8080 #host:container
    volumes:
      - ./:/app/app

  productservice:
    container_name: productService
    command: java -jar target/product-0.0.1-SNAPSHOT.jar
    build:
      context: productService/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./:/app/app

  currencyservice:
    container_name: currencyService
    command: java -jar target/currency-0.0.1-SNAPSHOT.jar
    build:
      context: currencyService/
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    volumes:
      - ./:/app/app

    

