version: "3.9"
services:
  warehouse:
    container_name: warehouse
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: warehouse/
      dockerfile: Dockerfile
    ports:
      - 9001:9001 #host:container
    volumes:
      - ./:/app/app

frontend:
  container_name: frontend
  command: /bin/sh -c "yarn serve"
  build:
    context: frontend/
    dockerfile: Dockerfile
  ports:
    - 8081:8081
  volumes:
    - ./:/app
    - node_modules:/app/node_modules
    - dist:/app/dist
